#!/usr/bin/env python3
"""Generate Adafruit-GFX font headers from a (variable) TTF via freetype-py.
Mirrors Adafruit fontconvert: 141 DPI, mono rendering, glyphs 0x20..0x7E,
yOffset = 1 - bitmap_top. Used to give the Poster theme its condensed UI
voice (same family as the big display faces).

  python3 genfont.py <ttf> <outfile.h> <Name>:<pt>:<wght> [more fonts...]
  e.g. genfont.py RC.ttf ../RobotoCondensedUI.h RobotoCondensedUI_Black18pt7b:18:900
"""
import sys, freetype

def gen(face_path, name, pt, wght):
    face = freetype.Face(face_path)
    try:
        # instance the variable font at the requested weight
        face.set_var_design_coords((float(wght),))
    except Exception:
        pass                                   # static font: keep as-is
    face.set_char_size(pt * 64, 0, 141, 0)

    bitmaps = bytearray()
    glyphs = []
    bitpos = 0
    for code in range(0x20, 0x7F):
        face.load_char(chr(code), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
        g = face.glyph
        bm = g.bitmap
        w, h, pitch = bm.width, bm.rows, bm.pitch
        offset = len(bitmaps) * 8 - bitpos     # we track in bits below instead
        start_bit = bitpos
        for y in range(h):
            for x in range(w):
                bit = (bm.buffer[y * pitch + (x >> 3)] >> (7 - (x & 7))) & 1
                if bitpos >> 3 >= len(bitmaps): bitmaps.append(0)
                if bit: bitmaps[bitpos >> 3] |= 0x80 >> (bitpos & 7)
                bitpos += 1
        glyphs.append(dict(off=start_bit // 8 if start_bit % 8 == 0 else None,
                           start_bit=start_bit, w=w, h=h,
                           xa=g.advance.x >> 6, xo=g.bitmap_left,
                           yo=1 - g.bitmap_top, code=code))
    # Adafruit format wants byte offsets: repack each glyph byte-aligned.
    packed = bytearray()
    for gl in glyphs:
        gl['off'] = len(packed)
        nbits = gl['w'] * gl['h']
        acc = 0
        for i in range(nbits):
            sb = gl['start_bit'] + i
            bit = (bitmaps[sb >> 3] >> (7 - (sb & 7))) & 1
            if i % 8 == 0: packed.append(0)
            if bit: packed[-1] |= 0x80 >> (i & 7)
    y_advance = face.size.height >> 6

    out = []
    out.append(f"// {name}  ({pt}pt, wght {wght}, {len(packed)} bytes) — generated by tools/genfont.py")
    out.append(f"const uint8_t {name}Bitmaps[] PROGMEM = {{")
    for i in range(0, len(packed), 12):
        out.append("  " + ", ".join("0x%02X" % b for b in packed[i:i+12]) + ",")
    out[-1] = out[-1].rstrip(",") + " };"
    out.append("")
    out.append(f"const GFXglyph {name}Glyphs[] PROGMEM = {{")
    for gl in glyphs:
        c = chr(gl['code']) if gl['code'] != 0x5C else 'backslash'
        out.append("  { %5d, %3d, %3d, %3d, %4d, %4d },   // 0x%02X %s" %
                   (gl['off'], gl['w'], gl['h'], gl['xa'], gl['xo'], gl['yo'], gl['code'], c))
    out[-1] = out[-1].replace("},", "} };", 1)
    out.append("")
    out.append(f"const GFXfont {name} PROGMEM = {{")
    out.append(f"  (uint8_t  *){name}Bitmaps,")
    out.append(f"  (GFXglyph *){name}Glyphs,")
    out.append(f"  0x20, 0x7E, {y_advance} }};")
    out.append("")
    return "\n".join(out)

if __name__ == "__main__":
    ttf, outfile = sys.argv[1], sys.argv[2]
    parts = ["// Generated by tools/genfont.py — condensed UI voice for the Poster theme.",
             "#pragma once", ""]
    for spec in sys.argv[3:]:
        name, pt, wght = spec.split(":")
        parts.append(gen(ttf, name, int(pt), int(wght)))
        print("generated", name)
    with open(outfile, "w") as f:
        f.write("\n".join(parts))
    print("wrote", outfile)
